[package]
name = "d19"
version = "0.1.0"
authors = ["imDema <luca.de.martini@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# petgraph = "0.5"
lazy_static = "1.4"
regex = "1.4"
